version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: oa_review
      MYSQL_ROOT_PASSWORD: mozezhao
      MYSQL_ROOT_HOST: '%'
    restart: always
    ports:
      - "3307:3306"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db